### PR TITLE
Change React linting version to ‘detect’ for flexibility - 9.6.0

### PR DESCRIPTION
**Pull request by wheeler**
Also bump some minor `eslint-plugin-react`

- [x] test this works against ZP

### CODE REVIEW

**Comment by rylanc** [comment]
@wheeler Have you had a chance to test this in ZP?

**Comment by wheeler** [comment]
@rylanc no, too many other changes required because of prettier changes. You can approve and I can promise not to merge until I test. Or we can remove reviewer until it is tested. Up to you.

**Comment by zp-alfred** [comment]
Accepted by rylanc!

**Comment by wheeler** [comment]
fixes #15

**Pull request merged**
