### PR TITLE
Switch to Yarn

### PR DESCRIPTION
**Pull request by kurtzur**

### CODE REVIEW

**Comment by kurtzur** [comment]
@zp-alfred needs revision

**Comment by zp-alfred** [comment]
Changes requested by kurtzur.

**Comment by kurtzur** [comment]
@zp-alfred review requested

**Comment by rylanc** [comment]
@kurtzur looks like i may have stepped on your toes a few days ago. It would still be handy to have the README changes though.

**Comment by rylanc** [comment]
@zp-alfred accept!

**Comment by zp-alfred** [comment]
Accepted by rylanc!

**Comment by rylanc** [comment]
@kurtzur Is this PR still relevant? Can we close it?

**Pull request closed without merging**
